### ISSUE TITLE
Error when trying to install the requirements

### ISSUE THREAD

**Issue by vkouam** [mk-minchul/AdaFace#140]
Hello,

I'm receiving the following error message, when trying to start the validation after the installation of the requirements from the file 'requirements.txt'. I also get an issue with the 'np.bool_' from the numpy code, it seems to be deprecated.

Does please anyone have tips, how I could fix these issues? 

Thanks in advance!

Best regards

_

> 
> Traceback (most recent call last):
>   File "main.py", line 12, in <module>
>     import train_val
>   File "/adaface/train_val.py", line 6, in <module>
>     import evaluate_utils
>   File "/adaface/evaluate_utils.py", line 6, in <module>
>     from sklearn.model_selection import KFold
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/sklearn/__init__.py", line 83, in <module>
>     from .base import clone
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/sklearn/base.py", line 19, in <module>
>     from .utils import _IS_32BIT
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 22, in <module>
>     from ._param_validation import Interval, validate_params
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 15, in <module>
>     from .validation import _is_arraylike_not_scalar
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/sklearn/utils/validation.py", line 28, in <module>
>     from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/sklearn/utils/_array_api.py", line 9, in <module>
>     from .fixes import parse_version
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 18, in <module>
>     import scipy.stats
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/scipy/stats/__init__.py", line 467, in <module>
>     from ._stats_py import *
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 39, in <module>
>     from scipy.spatial.distance import cdist
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 105, in <module>
>     from ._kdtree import *
>   File "/miniconda3/envs/_adaface/lib/python3.8/site-packages/scipy/spatial/_kdtree.py", line 5, in <module>
>     from ._ckdtree import cKDTree, cKDTreeNode
> ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/stfrsouo/miniconda3/envs/_adaface/lib/python3.8/site-packages/scipy/spatial/_ckdtree.cpython-38-x86_64-linux-gnu.so)

_

**Comment by vkouam** [comment]
I just updated Conda and matplotlib and it worked

**Comment by vkouam** [comment]
When started the training I still get the same error message.

**Comment by vkouam** [comment]
I reinstalled scikit-learn with the command bellow and it worked.

_pip install scikit-learn --no-cache-dir --force-reinstall_
