### ISSUE TITLE
PyTorch issue in requirements.txt

### ISSUE THREAD

**Issue by joelb92** [mk-minchul/AdaFace#151]
When performing a 
`pip install -r requirements.txt`
on Ubuntu 22.04 with python 3.10, we receive this error

```
 × Running setup.py install for pytorch did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5380e9mr/pytorch_738d7a5252c5452a8062cfd877cfb51c/setup.py", line 11, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]
```

**Comment by mosidd-01** [comment]
It seems `pytorch` has been renamed to `torch` so I modified the file `requirements.txt` to the following and I was able to get it working

```
pytorch-lightning==1.8.6
torch>=1.9.0
tqdm
bcolz-zipline
prettytable
menpo
mxnet
opencv-python
```
