### ISSUE TITLE
How to solve？can't find this file（mem_file.dat.conf）

### ISSUE THREAD

**Issue by xingjunhong** [mk-minchul/AdaFace#40]
I tried to train after processing the data according to the convert.py script you provided, but I couldn't find the MEM of the validation set_ File.dat.conf file

initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 1 processes
----------------------------------------------------------------------------------------------------

creating train dataset
creating val dataset
laoding validation data memfile
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    main(args)
  File "main.py", line 55, in main
    trainer.fit(trainer_mod, data_mod)
  File "/my_app/anaconda3/envs/06.adaface-pytorch1.8-python3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/my_app/anaconda3/envs/06.adaface-pytorch1.8-python3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 865, in _run
    self._call_setup_hook(model)  # allow user to setup lightning_module in accelerator environment
  File "/my_app/anaconda3/envs/06.adaface-pytorch1.8-python3.7/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1169, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/my_app/anaconda3/envs/06.adaface-pytorch1.8-python3.7/lib/python3.7/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/work/1.model_train/6.face/AdaFace-master/data.py", line 99, in setup
    self.val_dataset = val_dataset(self.data_root, self.val_data_path, self.concat_mem_file_name)
  File "/work/1.model_train/6.face/AdaFace-master/data.py", line 136, in val_dataset
    val_data = evaluate_utils.get_val_data(os.path.join(data_root, val_data_path))
  File "/work/1.model_train/6.face/AdaFace-master/evaluate_utils.py", line 12, in get_val_data
    agedb_30, agedb_30_issame = get_val_pair(data_path, 'agedb_30')
  File "/work/1.model_train/6.face/AdaFace-master/evaluate_utils.py", line 25, in get_val_pair
    np_array = read_memmap(mem_file_name)
  File "/work/1.model_train/6.face/AdaFace-master/evaluate_utils.py", line 53, in read_memmap
    with open(mem_file_name+'.conf', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'faces_emore/agedb_30/memfile/mem_file.dat.conf'

**Comment by raha-2020** [comment]
Hi, 
How did you solve it, I am unable to understand? Could you help me out? How do I create one ?
@xingjunhong @mk-minchul

**Comment by mk-minchul** [comment]
For those who are encountering the same error, this error message is created if the validation set is not prepared properly. 
To prepare the validation set, 
1. download `CASIA-Webface` dataset from InsightFace link provided in the README_Train.md.
2. This file contains `faces_webface_112x112.zip` and unzip it.
3. Preprocess the 5 validation sets using 
```python convert.py --rec_path <path_to_data_root>/faces_webface_112x112 --make_validation_memfiles```
 4. run training code with 
 ```python main.py ... --data_root <path_to_data_root> --val_data_path faces_webface_112x112```
 
 While running the training code, the mem files are generated. They are generated to prevent the validation sets from being loaded into the memory all at the same time.

**Comment by raha-2020** [comment]
Thank you @mk-minchul
