### ISSUE TITLE
ValueError: You selected an invalid accelerator name: `accelerator='ddp'`. Available names are: cpu, cuda, hpu, ipu, mps, tpu.

### ISSUE THREAD

**Issue by WOTMCCR** [mk-minchul/AdaFace#70]
i don't know how to use gpu

**Comment by mk-minchul** [comment]
Hi WOTMCCR

This error is due to the update in pytorch lightning. 
You could use the `pytorch-lightning==1.4.4 ` to use the existing code.
Or if you would like to use the up-to-date pytorch-lightning,
`accelerator` should receive `gpu` and `strategy` should receive `ddp`.
Until I update the code you can change the code at line https://github.com/mk-minchul/AdaFace/blob/master/main.py#L47 to be 
```
pl.Trainer(
...
     accelerator="gpu"
     strategy="ddp",
...
)
```

**Comment by mk-minchul** [comment]
code is updated as well.

**Comment by rsj123** [comment]
After update the code, I got this error:
```
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main(args)
  File "main.py", line 55, in main
    limit_train_batches=50 if hparams.test_run else 1.0
  File "/root/miniconda3/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 40,in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'strategy'
```

**Comment by mk-minchul** [comment]
Thanks for the notice!
I have updated the code for backward compatibility.
